project_id = "fbpbnpleczgondniojmy"

[functions.analyze-hazard]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.get-route]
verify_jwt = false

[functions.analyze-route-safety]
verify_jwt = false

[functions.cleanup-old-hazards]
verify_jwt = false